# Generated by Django 3.2.7 on 2021-09-30 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audibledevice',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='audibledevice',
            old_name='created',
            new_name='created_at',
        ),
    ]
